FS_BASE_REST_URL = "https://sg5.fusionsolar.huawei.com"
FS_API_PATH = "/thirdData/login"
FUSIONSOLAR_USERNAME = "xxxx"
FUSIONSOLAR_PASSWORD = "xxxxx"
FS_COMPLETE_REST_URL = FS_BASE_REST_URL + FS_API_PATH

ENVISION_ACCESS_KEY = "xxxxx"
ENVISION_SECRET_KEY = "xxxxx"
ENVISION_USERNAME = "xxxxx"
ENVISION_PASSWORD = "xxxxx"
